# https://github.com/Huachao/vscode-restclient/blob/master/README.md#usage
POST http://localhost:3003/api/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcmUiLCJpZCI6IjYyOTNhNTRkY2ZlMDNlZTMzMDE5M2RjZiIsImlhdCI6MTY1ODE3NTUwMywiZXhwIjoxNjU4MTc5MTAzfQ.gyrRwZbv5egMXKcqFgzUID3IsGU1xEew817Up_iIGUY
Content-Type: application/json

{
    "username": "Lare",
    "name": "Mika Le Gall",
    "password": "salasana"
}
