POST http://localhost:3003/api/testing/reset
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcmUiLCJpZCI6IjYyOTBjYjQ4MTVmNWE5NjcyOWY1NzEwYiIsImlhdCI6MTY1OTI1MDMzOSwiZXhwIjoxNjU5MjUzOTM5fQ.KeqGAt5UFkEXsOmupkiKl0yHaIpN37ZAW4lGcLebzis
