# https://github.com/Huachao/vscode-restclient/blob/master/README.md#usage
PUT http://localhost:3003/api/blogs/62a1bd7f03233304a27f024f
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcmUiLCJpZCI6IjYyOTNhNTRkY2ZlMDNlZTMzMDE5M2RjZiIsImlhdCI6MTY1ODE3NTUwMywiZXhwIjoxNjU4MTc5MTAzfQ.gyrRwZbv5egMXKcqFgzUID3IsGU1xEew817Up_iIGUY

{
    "title": "uusi yritys!",
    "author": "testaajan teppo",
    "url": "https://pakollinen1234.wordpress.com/2021/04/11/digitaalinen-viestinta/",
    "likes": 2
}